### ISSUE TITLE
Lens Moving Slow

### ISSUE THREAD

**Issue by prasad8801** [payalord/xZoom#5]
When i mouse hover thumbnail image the preview image moving slowly parallel with thumb image. Can you help me on this?

**Comment by payalord** [comment]
Yes, but i need more details on this issue.
* have you tried to set option **smoothZoomMove** to 1?
* what xZoom version (probably the last, but just in case)?
* what browser/version you experienced this issue? I'll try to replicate it on my end here. If it is a bug I'll fix it, then will make new patch release.

**Comment by prasad8801** [comment]
Can you look into following url.
https://sav.dotcomweavers.net/us-army-ar01.html
we are not getting this issue alone your code. when we are integrating with magento we are facing issue.

**Comment by payalord** [comment]
CSS file: https://sav.dotcomweavers.net/skin/frontend/tm_themes/theme349k/css/styles.css
Line 2407:
```css
img {
    -webkit-transition: all .8s ease-in-out;
    -moz-transition: all .8s ease-in-out;
    -o-transition: all .8s ease-in-out;
    transition: all .8s ease-in-out
}
```
Looks like this is the problem of slow mo. I don't know do you need this styles on all images on the page or not. But if yes then reset this styles inside xzoom css for xzoom images so this css transition will not affect them.
